server:
  port: 8000
spring:
  application:
    name: exchange-service
  cloud:
    config:
      enabled: false
    datasource:
      driver-class-name: org.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/exchange_service?useTimezone=true&ServerTimezone=UTC
      username: ${DB_USER}
      password: ${DB_PASS}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    flyway:
      url: jdbc:mysql://localhost:3306/
      schemas: exchange_service
      user: ${DB_USER}
      password: ${DB_PASS}