server:
  port: 8000
spring:
  application:
    name: exchange-service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/exchange_service?useTimezone=true&ServerTimezone=UTC
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  flyway:
      url: jdbc:mysql://localhost:3306/
      schemas: exchange_service
      user: ${DB_USER}
      password: ${DB_PASSWORD}